controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_vehicle_detail:
    path: /vehicle/{slug}
    controller: App\Controller\VehicleController::detail

